### ISSUE TITLE
支持通过 limit + offset / limit + id 的方式获取消息记录

### ISSUE THREAD

**Issue by dousha** [cssxsh/mirai-hibernate-http#2]
考虑到一些群可能并不活跃（或者过于活跃），单纯使用时间区域可能选中过少（或者过多）消息数量，也并不便于实现下滑加载更多历史消息。可以考虑实现 limit + offset / limit + id 的方式返回从某处开始最多 n 条消息记录。

考虑到性能，最好实现 limit + id 方式（如果 id 是有序的话）。

**Comment by cssxsh** [comment]
`limit + time` 可以吗

**Comment by dousha** [comment]
> `limit + time` 可以吗

这个 `time` 是起始时间还是结束时间？

**Comment by cssxsh** [comment]
结束时间和起始时间都行

实际上 `limit + offset` 也挺容易实现的
我可以都写了
`limit + offset`
`limit + start`
`limit + end`

https://github.com/cssxsh/mirai-hibernate-http/blob/e4b070de2cc8182a1d6e288374c55a559ecd3ef9/src/main/kotlin/xyz/cssxsh/mirai/hibernate/http/HibernateAdapter.kt#L120-L147
