### ISSUE TITLE
是否可以直接根据消息id取得指定消息呢？

### ISSUE THREAD

**Issue by Natsukage** [cssxsh/mirai-hibernate-http#4]
如题，比如我想要获取群聊中某一个quote消息对应的原始消息，获取其中的图片。
Quote的origin中的消息已经被转义，所以通过消息自己的origin是无法取得图片的内容的，并且也并不知道对应消息的发送时间。

```
{
  "type": "Quote",
  "id": "34387",
  "groupId": "4****5",
  "senderId": "4****2",
  "targetId": "4****5",
  "origin": [
    {
      "text": "确实[图片]",
      "type": "Plain"
    }
  ]
}
```
所以无法使用`/message/source?target={}&time={}&ids={}`获取对应的消息。

想问一下，像这种只有对应消息ID的情况，要查特定的这一条消息内容而不是一个时间段内的消息的话，应该如何获取呢？

**Comment by cssxsh** [comment]
这是 mirai-api-http 返回的内容？
居然不带 time

我下个版本把 time 弄成可选的吧

**Comment by Natsukage** [comment]
上面例子是我解析过后的，里面一部分参数大小写有变化，但是结构和内容是完全一样的，里面没有包含time
可以参考[MAH的文档](https://docs.mirai.mamoe.net/mirai-api-http/api/MessageType.html#quote)

**Comment by cssxsh** [comment]
https://github.com/cssxsh/mirai-hibernate-http/actions/runs/4500128453

不过注意一点就是，我这个 返回的消息数据结构可能和和 MAH 不一样，用的是mirai原生的序列化

**Comment by Natsukage** [comment]
好的，多谢！辛苦了！
